version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '8080:80'
    depends_on:
      - mysqlserver
    networks:
      - network-database
    environment:
       MYSQL_HOST: "mysqlserver"
       MYSQL_PORT: '3306'
       MYSQL_USER: root
       MYSQL_PASSWORD: password
       MYSQL_DB: ecom

  mysqlserver:
    image: mysql/mysql-server
    restart: unless-stopped

    #uncomment following lines to access db locally
    #ports:
    #   - 3306:3306
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    networks:
      - network-database
    environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: ecom
         MYSQL_USER: root
         MYSQL_PASSWORD: password

  adminer:
      image: adminer
      restart: always
      ports:
        - 8090:8080
      networks:
        - network-database

#volumes:
#  sql_data:

networks:
  network-database:



